export type WordCard = { word: string; hint: string }
export type QuestionCard = { real: string; alternate: string }

export const wordCards: WordCard[] = [
  { word: 'Strand', hint: 'Sommer' },
  { word: 'Biograf', hint: 'Film' },
  { word: 'Tandlæge', hint: 'Sundhed' },
  { word: 'Camping', hint: 'Ferie' },
  { word: 'Fødselsdag', hint: 'Fest' },
  { word: 'Bibliotek', hint: 'Bøger' },
  { word: 'Lufthavn', hint: 'Rejse' },
  { word: 'Pizza', hint: 'Mad' },
  { word: 'Snebold', hint: 'Vinter' },
  { word: 'Bryllup', hint: 'Fejring' },
  { word: 'Cirkus', hint: 'Underholdning' },
  { word: 'Supermarked', hint: 'Indkøb' },
  { word: 'Svømmehal', hint: 'Vand' },
  { word: 'Museum', hint: 'Udstilling' },
  { word: 'Togstation', hint: 'Transport' },
  { word: 'Kaffemaskine', hint: 'Morgen' },
  { word: 'Forlystelsespark', hint: 'Tur' },
  { word: 'Regnbue', hint: 'Vejr' },
  { word: 'Skattekiste', hint: 'Eventyr' },
  { word: 'Fodbold', hint: 'Sport' },
  { word: 'Juletræ', hint: 'December' },
  { word: 'Vulkan', hint: 'Natur' },
  { word: 'Rumraket', hint: 'Rummet' },
  { word: 'Pandekager', hint: 'Morgenmad' },
]

export const questionCards: QuestionCard[] = [
  { real: 'Hvad er det bedste ved sommeren?', alternate: 'Hvad er det værste ved vinteren?' },
  { real: 'Hvad ville du tage med til en øde ø?', alternate: 'Hvad ville du tage med på en skiferie?' },
  { real: 'Hvilken mad kunne du spise hver dag?', alternate: 'Hvilken mad ville du aldrig bestille?' },
  { real: 'Hvad gør en god fest uforglemmelig?', alternate: 'Hvad gør en dårlig fest uforglemmelig?' },
  { real: 'Hvilket dyr ville være det bedste kæledyr?', alternate: 'Hvilket dyr ville være den bedste livvagt?' },
  { real: 'Hvad ville du købe, hvis du vandt en million?', alternate: 'Hvad ville du sælge, hvis du manglede penge?' },
  { real: 'Hvad er den bedste ting at lave på en regnvejrsdag?', alternate: 'Hvad er den bedste ting at lave på en solskinsdag?' },
  { real: 'Hvilken ting bruger du mest tid på om morgenen?', alternate: 'Hvilken ting bruger du mest tid på om aftenen?' },
  { real: 'Hvor ville du helst holde ferie?', alternate: 'Hvor ville du nødigt bo et helt år?' },
  { real: 'Hvad er det vigtigste i en god film?', alternate: 'Hvad er det vigtigste i et godt spil?' },
  { real: 'Hvad ville du gøre først på din fridag?', alternate: 'Hvad ville du gøre først på din arbejdsdag?' },
  { real: 'Hvilken superkraft ville du vælge?', alternate: 'Hvilken superkraft ville være mest besværlig?' },
  { real: 'Hvad er den bedste gave at få?', alternate: 'Hvad er den sværeste gave at give?' },
  { real: 'Hvad gør en restaurant god?', alternate: 'Hvad gør et hotel godt?' },
  { real: 'Hvad ville du lære, hvis du havde et år fri?', alternate: 'Hvad ville du lære, hvis du kun havde en dag?' },
  { real: 'Hvad er den bedste måde at komme rundt i byen på?', alternate: 'Hvad er den bedste måde at rejse langt på?' },
  { real: 'Hvad er det bedste at spise til morgenmad?', alternate: 'Hvad er det bedste at spise til aftensmad?' },
  { real: 'Hvad ville du gøre, hvis du var usynlig i en dag?', alternate: 'Hvad ville du gøre, hvis du kunne flyve i en dag?' },
  { real: 'Hvad gør en ven god?', alternate: 'Hvad gør en kollega god?' },
  { real: 'Hvilken ting ville du redde fra et brændende hus?', alternate: 'Hvilken ting ville du pakke først til en flytning?' },
]
