export type WordCard = { word: string; hint: string }
export type QuestionCard = { real: string; alternate: string }

export const wordCards: WordCard[] = [
  { word: 'Strand', hint: 'Sommer' },
  { word: 'Biograf', hint: 'Film' },
  { word: 'Tandlæge', hint: 'Sundhed' },
  { word: 'Camping', hint: 'Ferie' },
  { word: 'Fødselsdag', hint: 'Fest' },
  { word: 'Bibliotek', hint: 'Bøger' },
  { word: 'Lufthavn', hint: 'Rejse' },
  { word: 'Pizza', hint: 'Mad' },
  { word: 'Snebold', hint: 'Vinter' },
  { word: 'Bryllup', hint: 'Fejring' },
  { word: 'Cirkus', hint: 'Underholdning' },
  { word: 'Supermarked', hint: 'Indkøb' },
  { word: 'Svømmehal', hint: 'Vand' },
  { word: 'Museum', hint: 'Udstilling' },
  { word: 'Togstation', hint: 'Transport' },
  { word: 'Kaffemaskine', hint: 'Morgen' },
  { word: 'Forlystelsespark', hint: 'Tur' },
  { word: 'Regnbue', hint: 'Vejr' },
  { word: 'Skattekiste', hint: 'Eventyr' },
  { word: 'Fodbold', hint: 'Sport' },
  { word: 'Juletræ', hint: 'December' },
  { word: 'Vulkan', hint: 'Natur' },
  { word: 'Rumraket', hint: 'Rummet' },
  { word: 'Pandekager', hint: 'Morgenmad' },
]

export const questionCards: QuestionCard[] = [
  { real: 'Hvad er det bedste ved sommeren?', alternate: 'Hvad er det værste ved vinteren?' },
  { real: 'Hvad ville du tage med til en øde ø?', alternate: 'Hvad ville du tage med på en skiferie?' },
  { real: 'Hvilken mad kunne du spise hver dag?', alternate: 'Hvilken mad ville du aldrig bestille?' },
  { real: 'Hvad gør en god fest uforglemmelig?', alternate: 'Hvad gør en dårlig fest uforglemmelig?' },
  { real: 'Hvilket dyr ville være det bedste kæledyr?', alternate: 'Hvilket dyr ville være den bedste livvagt?' },
  { real: 'Hvad ville du købe, hvis du vandt en million?', alternate: 'Hvad ville du sælge, hvis du manglede penge?' },
  { real: 'Hvad er den bedste ting at lave på en regnvejrsdag?', alternate: 'Hvad er den bedste ting at lave på en solskinsdag?' },
  { real: 'Hvilken ting bruger du mest tid på om morgenen?', alternate: 'Hvilken ting bruger du mest tid på om aftenen?' },
  { real: 'Hvor ville du helst holde ferie?', alternate: 'Hvor ville du nødigt bo et helt år?' },
  { real: 'Hvad er det vigtigste i en god film?', alternate: 'Hvad er det vigtigste i et godt spil?' },
  { real: 'Hvad ville du gøre først på din fridag?', alternate: 'Hvad ville du gøre først på din arbejdsdag?' },
  { real: 'Hvilken superkraft ville du vælge?', alternate: 'Hvilken superkraft ville være mest besværlig?' },
  { real: 'Hvad er den bedste gave at få?', alternate: 'Hvad er den sværeste gave at give?' },
  { real: 'Hvad gør en restaurant god?', alternate: 'Hvad gør et hotel godt?' },
  { real: 'Hvad ville du lære, hvis du havde et år fri?', alternate: 'Hvad ville du lære, hvis du kun havde en dag?' },
  { real: 'Hvad er den bedste måde at komme rundt i byen på?', alternate: 'Hvad er den bedste måde at rejse langt på?' },
  { real: 'Hvad er det bedste at spise til morgenmad?', alternate: 'Hvad er det bedste at spise til aftensmad?' },
  { real: 'Hvad ville du gøre, hvis du var usynlig i en dag?', alternate: 'Hvad ville du gøre, hvis du kunne flyve i en dag?' },
  { real: 'Hvad gør en ven god?', alternate: 'Hvad gør en kollega god?' },
  { real: 'Hvilken ting ville du redde fra et brændende hus?', alternate: 'Hvilken ting ville du pakke først til en flytning?' },
  { real: 'Hvilken kunstner ville du høre resten af dit liv?', alternate: 'Hvilken kunstner lyttede du sidst til?' },
  { real: 'Hvilken sang kan altid få dig i godt humør?', alternate: 'Hvilken sang har du hørt flest gange?' },
  { real: 'Hvilken koncert ville du allerhelst opleve?', alternate: 'Hvilken kunstner tror du er bedst live?' },
  { real: 'Hvilken musikgenre passer bedst til en fest?', alternate: 'Hvilken musikgenre passer bedst til en køretur?' },
  { real: 'Hvilken film kunne du se igen og igen?', alternate: 'Hvilken film så du senest?' },
  { real: 'Hvilken serie ville du ønske, du kunne se for første gang igen?', alternate: 'Hvilken serie brugte du sidst en hel dag på?' },
  { real: 'Hvilken kendt person ville du helst spise middag med?', alternate: 'Hvilken kendt person ville du helst bytte liv med?' },
  { real: 'Hvilken app ville være sværest at undvære?', alternate: 'Hvilken app åbnede du senest?' },
  { real: 'Hvilket socialt medie bruger du mest?', alternate: 'Hvilket socialt medie ville du helst slette?' },
  { real: 'Hvilket spil er du bedst til?', alternate: 'Hvilket spil har du brugt mest tid på?' },
  { real: 'Hvad er din bedste undskyldning for at komme for sent?', alternate: 'Hvad er den mest almindelige grund til, at du kommer for sent?' },
  { real: 'Hvad ville du bruge en uventet fridag på?', alternate: 'Hvad brugte du din seneste fridag på?' },
  { real: 'Hvad er det første, du gør, når du vågner?', alternate: 'Hvad er det sidste, du gør, før du sover?' },
  { real: 'Hvad ville du være kendt for?', alternate: 'Hvad tror du, dine venner kender dig bedst for?' },
  { real: 'Hvilket job ville du være overraskende god til?', alternate: 'Hvilket job ville du aldrig kunne holde ud?' },
  { real: 'Hvilket fag burde alle have i skolen?', alternate: 'Hvilket fag var du bedst til i skolen?' },
  { real: 'Hvad ville du købe først, hvis du fik 10.000 kroner?', alternate: 'Hvad er det dyreste, du har købt det seneste år?' },
  { real: 'Hvilken by ville du helst vågne op i i morgen?', alternate: 'Hvilken by besøgte du senest?' },
  { real: 'Hvilket land har den bedste mad?', alternate: 'Hvilket land ville du helst rejse til næste gang?' },
  { real: 'Hvad er den bedste snack til en filmaften?', alternate: 'Hvilken snack købte du senest?' },
  { real: 'Hvilken ret ville du imponere en date med?', alternate: 'Hvilken ret er du bedst til at lave?' },
  { real: 'Hvad bestiller du oftest som takeaway?', alternate: 'Hvad ville du bestille lige nu?' },
  { real: 'Hvilken ting er altid i dit køleskab?', alternate: 'Hvilken ting mangler oftest i dit køleskab?' },
  { real: 'Hvilket dyr minder mest om din personlighed?', alternate: 'Hvilket dyr ville dine venner sammenligne dig med?' },
  { real: 'Hvad ville du gøre under en zombieapokalypse?', alternate: 'Hvad ville du gøre under en strømafbrydelse?' },
  { real: 'Hvad ville du ønske dig, hvis du fik ét ønske?', alternate: 'Hvad ønskede du dig mest som barn?' },
  { real: 'Hvilken alder ville du helst være for evigt?', alternate: 'Hvor gammel var du, da du havde dit bedste år?' },
  { real: 'Hvor gammel var du, da du fik din første telefon?', alternate: 'Sig et tal mellem 8 og 18.' },
  { real: 'Hvor gammel var du, da du lærte at cykle?', alternate: 'Sig et tal mellem 3 og 10.' },
  { real: 'Hvor mange timer sover du på en god nat?', alternate: 'Sig et tal mellem 5 og 10.' },
  { real: 'Hvor mange lande tror du, du har besøgt?', alternate: 'Sig et tal mellem 1 og 20.' },
  { real: 'Hvor mange minutter bruger du på at blive klar om morgenen?', alternate: 'Sig et tal mellem 10 og 60.' },
  { real: 'Hvor mange gange om ugen bestiller du mad udefra?', alternate: 'Sig et tal mellem 0 og 7.' },
  { real: 'Hvor mange alarmer sætter du om morgenen?', alternate: 'Sig et tal mellem 1 og 5.' },
  { real: 'På en skala fra 1 til 10, hvor konkurrencemenneske er du?', alternate: 'Sig et tal mellem 1 og 10.' },
  { real: 'På en skala fra 1 til 10, hvor god er du til at lyve?', alternate: 'Sig et tal mellem 1 og 10.' },
  { real: 'Hvor mange personer ville du invitere til den perfekte fest?', alternate: 'Sig et tal mellem 5 og 30.' },
  { real: 'Hvor meget ville du betale for den perfekte koncertbillet?', alternate: 'Sig et beløb mellem 200 og 2.000 kroner.' },
]
